### ISSUE TITLE
Error in Docker - started after last update

### ISSUE THREAD

**Issue by seaverd** [seanauff/metermon#10] opened 2021-05-31 21:06 UTC
I have been using your docker container successfully  for over a year to read both my electric and water meter.  I just updated my container after your last edit and now I get an error and the container stops.  Looks like its an issue with the R900 water meter.   Here is the output of the logs:

`Username and password set.
Connected to broker at 192.168.0.50:11883 with result code 0: Connection Accepted.
07:25:11.744718 flags.go:111: Environment variable "RTLAMR_FILTERID" overrides flag "filterid" with "1549283752,37004795"
07:25:11.745203 decode.go:45: CenterFreq: 912600155
07:25:11.745236 decode.go:46: SampleRate: 2359296
07:25:11.745290 decode.go:47: DataRate: 32768
07:25:11.745319 decode.go:48: ChipLength: 72
07:25:11.745343 decode.go:49: PreambleSymbols: 32
07:25:11.745374 decode.go:50: PreambleLength: 4608
07:25:11.745408 decode.go:51: PacketSymbols: 736
07:25:11.745414 decode.go:52: PacketLength: 105984
07:25:11.745417 decode.go:59: Protocols: scm+,idm,r900,scm
07:25:11.745429 decode.go:60: Preambles: 0001011010100011,01010101010101010001011010100011,00000000000000001110010101100100,111110010101001100000
07:25:11.745436 main.go:124: GainCount: 29
{"Protocol": "SCM", "Type": "Electric", "ID": "37004795", "Consumption": 468.71, "Unit": "kWh"}
Traceback (most recent call last):
File "./metermon.py", line 148, in <module>
msg[attr] = R900_LOOKUP[kind][value]
KeyError: 32`

Any help would be greatly appreciated!

Dan

**Comment by seanauff** [comment] 2021-05-31 21:16
I had merged #9, which looks to be the cause of the issue. I've reverted, though it will take some time to build the image.

**Comment by seanauff** [comment] 2021-05-31 21:24
Images are now updated, let me know if the issue still persists!

**Comment by seaverd** [comment] 2021-06-01 03:15
> Images are now updated, let me know if the issue still persists!

Thanks, just updated docker and everything works fine!

**Closed** 2021-06-01 12:45 UTC

**Comment by jjlawren** [comment] 2021-06-01 22:13
Sorry I broke this for you, @seaverd. Looks like some R900 meters can follow a slightly different specification: https://github.com/bemasher/rtlamr/issues/99.

This feels like something that should be addressed in `rtlamr` and I'm not confident on how to update #9 to work reliably for all R900 meters right now.
